package my_practice.leet_code.String;

public class FindTheDifference {
    public static char findTheDifference(String s, String t) {
        int sum = 0;
        // Subtract all s chars
        for (int i = 0; i < s.length(); i++) {
            sum -= s.charAt(i);
        }
        // Add all t chars
        for (int i = 0; i < t.length(); i++) {
            sum += t.charAt(i);
        }
        return (char) sum;
    }

    // Example usage:
    public static void main(String[] args) {
        System.out.println(findTheDifference("abcd", "abcde")); // e
        System.out.println(findTheDifference("", "y"));         // y
    }
}

/*You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.*/